#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jul 17 12:32:26 2024

@author: titi
"""
from pydantic import BaseModel
class Symptom(BaseModel):
    Symptom_1: float 
    Symptom_2: float 
    Symptom_3: float 
    Symptom_4: float
    Symptom_5: float
    Symptom_6: float
    Symptom_7: float
    Symptom_8: float
    Symptom_9: float
    Symptom_10: float
    Symptom_11: float
    Symptom_12: float
    Symptom_13: float
    Symptom_14: float
    Symptom_15: float
    Symptom_16: float
    Symptom_17: float
    Symptom_18: float 
    Symptom_19: float 
    Symptom_20: float 
    Symptom_21: float
    Symptom_22: float
    Symptom_23: float
    Symptom_24: float
    Symptom_25: float
    Symptom_26: float
    Symptom_27: float
    Symptom_28: float
    Symptom_29: float
    Symptom_30: float
    Symptom_31: float
    Symptom_32: float
    Symptom_33: float
    Symptom_34: float
    Symptom_35: float 
    Symptom_36: float 
    Symptom_37: float 
    Symptom_38: float
    Symptom_39: float
    Symptom_40: float
    Symptom_41: float
    Symptom_42: float
    Symptom_43: float
    Symptom_44: float
    Symptom_45: float
    Symptom_46: float
    Symptom_47: float
    Symptom_48: float
    Symptom_49: float
    Symptom_50: float
    Symptom_51: float
    Symptom_52: float 
    Symptom_53: float 
    Symptom_54: float 
    Symptom_55: float
    Symptom_56: float
    Symptom_57: float
    Symptom_58: float
    Symptom_59: float
    Symptom_60: float
    Symptom_61: float
    Symptom_62: float
    Symptom_63: float
    Symptom_64: float
    Symptom_65: float
    Symptom_66: float
    Symptom_67: float
    Symptom_68: float
    Symptom_69: float 
    Symptom_70: float 
    Symptom_71: float 
    Symptom_72: float
    Symptom_73: float
    Symptom_74: float
    Symptom_75: float
    Symptom_76: float
    Symptom_77: float
    Symptom_78: float
    Symptom_79: float
    Symptom_80: float
    Symptom_81: float
    Symptom_82: float
    Symptom_83: float
    Symptom_84: float
    Symptom_85: float
    Symptom_86: float 
    Symptom_87: float 
    Symptom_88: float 
    Symptom_89: float
    Symptom_90: float
    Symptom_91: float
    Symptom_92: float
    Symptom_93: float
    Symptom_94: float
    Symptom_95: float
    Symptom_96: float
    Symptom_97: float
    Symptom_98: float
    Symptom_99: float
    Symptom_100: float
    Symptom_101: float
    Symptom_102: float
    Symptom_103: float 
    Symptom_104: float 
    Symptom_105: float 
    Symptom_106: float
    Symptom_107: float
    Symptom_108: float
    Symptom_109: float
    Symptom_110: float
    Symptom_111: float
    Symptom_112: float
    Symptom_113: float
    Symptom_114: float
    Symptom_115: float
    Symptom_116: float
    Symptom_117: float
    Symptom_118: float
    Symptom_119: float
    Symptom_120: float 
    Symptom_121: float 
    Symptom_122: float 
    Symptom_123: float
    Symptom_124: float
    Symptom_125: float
    Symptom_126: float
    Symptom_127: float
    Symptom_128: float
    Symptom_129: float
    Symptom_130: float
    Symptom_131: float

